# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-20 18:58
from __future__ import unicode_literals

from django.db import migrations, models
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0002_auto_20150616_2121'),
        ('resources', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='for_total_beginners',
            field=models.BooleanField(choices=[(True, 'Tak'), (False, 'Nie')]),
        ),
    ]
