# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-20 19:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0003_auto_20160220_2024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='link',
            field=models.URLField(),
        ),
    ]
